package wasmcloud:ai;

world ai {
   import wasi:http/outgoing-handler@0.2.2;
   import wasi:cli/environment@0.2.2;
   export response-handler;
}

interface response-handler {    
    prompt-handle: func(prompt: string) -> string;
}
